import AppKit

@MainActor
protocol ClipboardMonitorDelegate: AnyObject {
    func clipboardDidChange(newItem: NSPasteboardItem)
}

@MainActor
class ClipboardMonitor {
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    
    weak var delegate: ClipboardMonitorDelegate?
    
    private let ignoredTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("com.agilebits.onepassword"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType")
    ]
    
    init() {
        self.lastChangeCount = pasteboard.changeCount
    }
    
    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.checkForChanges()
            }
        }
    }
    
    func stop() {
        timer?.invalidate()
        timer = nil
    }
    
    private func checkForChanges() {
        let currentChangeCount = pasteboard.changeCount
        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount
        
        guard let items = pasteboard.pasteboardItems, let firstItem = items.first else { return }
        
        for item in items {
            let types = item.types
            for ignored in ignoredTypes {
                if types.contains(ignored) {
                    return
                }
            }
        }
        
        delegate?.clipboardDidChange(newItem: firstItem)
    }
}
